camera:
  position: [0.0, 0.0, 0.0]  # Camera position is the origin
  orientation: [0.0, 0.0, 0.0]  # Camera has no rotation in absolute referential

pan_tilt_units:
  - name: "PanTilt1"
    position: [-0.05, -0.42, 0.0]  # Example position relative to camera
    orientation: [0.00, 0.0, 0.0]  # Orientation is zero (no rotation relative to camera)
    i2c_id: 0
    motors_id: [0, 1]

  - name: "PanTilt2"
    position: [0.05, -0.42, 0.0]  # Example position relative to camera
    orientation: [0.00, 0.0, 0.0]  # Orientation is zero (no rotation relative to camera)
    i2c_id: 0
    motors_id: [2, 3]

